#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m rule --add app="^(Calculator|System Settings|Archive Utility)$" manage=off
yabai -m rule --add app="^(choose|Signal|mpv|IINA|OBS)$" manage=off
yabai -m rule --add app="^(qemu-system-i386|qemu-system-x86_64)$" manage=off
# yabai -m rule --add app="^(CPU|RAM|Battery|Network|Disk)$" manage=off topmost=on

yabai -m config			\
    top_padding		8 	\
    left_padding	8 	\
    right_padding	8 	\
    bottom_padding	8 	\
    window_gap		8 	\
    layout			bsp \
	mouse_modifier  ctrl

echo "yabai configuration loaded..."
